baloan_url = "https://app.baloan.ir/login"
login_text = "با ورود و یا ثبت نام در بالون شما شرایط و قوانین استفاده از سرویس‌های سایت بالون را می‌پذیرید."
phone_number = "09931832108"
otp_code = "12345"    #temporary
national_code = "0019338562"
date = "1375/06/01"

#locator
phone_number_input = "id:phone_number"
otp_code_input = "id:password"
national_code_input = "name:national_identifier"
birthdate_input = "name:birthDate"
birthdate_month = "xpath://*[@class='rmdp-header-values']/span[@style][1]"
birthdate_year = "xpath://*[@class='rmdp-header-values']/span[@style][2]"
page_header = "css:h1"
date_picker = "css:.rmdp-wrapper"
year_picker = "class:rmdp-year-picker"
month_picker = "class:rmdp-month-picker"
year = "xpath://*[@class='rmdp-year-picker']//span[text()='۱۳۷۵']"
month = "xpath://*[@class='rmdp-month-picker']//span[text()='شهریور']"
day = "xpath://*[@class='rmdp-day-picker ']//span[text()='۱']"
shop = "css:.w-full img"
enable_btn = "xpath://*[contains(text(),'{}')]/parent::button"
checkbox_role = "css:.form-tick"